development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3
  username: root
  password: root
  host: 127.0.0.1	
production:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3
  username: root
  password: root
  host: 127.0.0.1
